# Jekyll Configuration
safe: true
source: .
destination: html
lsi: false
markdown: rdiscount
permalink: pretty
exclude:
    - bower_components
    - node_modules
    - less
    - chapter08
    - chapter12

name: "Mastering D3.js"
